In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\suraj\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\suraj\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\suraj\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\suraj\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\suraj\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
print(df)
df.head(10)

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY

In [4]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
print(df)
df.head(10)
df.tail(10)

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

     Age Sex      BP Cholesterol  Na_to_K   Drug
190   58   M    HIGH        HIGH   18.991  DrugY
191   23   M    HIGH        HIGH    8.011  drugA
192   72   M     LOW        HIGH   16.310  DrugY
193   72   M     LOW        HIGH    6.769  drugC
194   46   F    HIGH         NaN   34.686  DrugY
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [7]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
df['Age'].dtype
df.dtypes

Age              int64
Sex                str
BP                 str
Cholesterol        str
Na_to_K        float64
Drug               str
dtype: object

In [8]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
df.shape
print("Total records:",len(df))

Total records: 200

In [9]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
df.size

1200

In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [12]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    str
 2   BP           200 non-null    str
 3   Cholesterol  199 non-null    str
 4   Na_to_K      200 non-null    float64
 5   Drug         199 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 9.5 KB

In [13]:
import pandas as pd
df = pd.read_csv(r"C:\Users\suraj\Downloads\drug200.csv")
print(df.iloc[0])
print(df.iloc[5:10])

Age                23
Sex                 F
BP               HIGH
Cholesterol      HIGH
Na_to_K        25.355
Drug            DrugY
Name: 0, dtype: object
   Age Sex      BP Cholesterol  Na_to_K   Drug
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY